#!/usr/bin/python3

"""
This program is part of MoaT.
Its job is simply to extract values from a YAML-formatted config file.
"""

from Cfg import Cfg
import sys

def main(f,*kk):
    s = Cfg(f)
    if kk:
        mode = ""
        for k in kk:
            if mode == "":
                if k[0] == '.':
                    if k == '.devs':
                        print(" ".join(sorted(k for k in s.subtree("devices") if not k.startswith('_'))))
                    else:
                        mode = k[1:]
                else:
                    did=[]
                    ks = k.split('.')
                    res = s.subtree(*ks)
                    if isinstance(res,dict):
                        print(" ".join("{}={}".format(a,v) for a,v in s.keyval(*ks)))
                    elif isinstance(res,(list,tuple)):
                        print(" ".join(str(x) for x in res))
                    else:
                        try:
                            f = float(res)
                        except Exception:
                            print(res)
                        else:
                            g = int(f)
                            if float(g) == f:
                                print(g)
                            else:
                                print(f)
            elif mode == "hdr":
                with open("device/"+k+"/dev_config.h","w") as f:
                    print("""\
#ifndef device_{}_config_h
#define device_{}_config_h

/*
 * This file is auto-generated. It contains a mix of global and local
 * definitions because I am lazy.
 *
 * Do not edit. Talk to 'moat.cfg' instead.
 */
    """.format(k,k), file=f);
                    i = 0
                    typecode = {}
                    for a in s.subtree('codes','types'):
                        typecode[a]=i
                        i += 1
                    i = 0x70
                    for a in s.subtree('codes','types_x70'):
                        typecode[a]=i
                        print("#define TC_{} {}".format(a.upper(),i), file=f)
                        i += 1

                    i = 1
                    print("typedef enum _ConfigID {", file=f);
                    for a in s.subtree('codes','blocks'):
                        typecode[a]=i
                        print("    CfgID_{} = {},".format(a,i), file=f)
                        i += 1
                    print("} ConfigID;", file=f);

                    for a,v in s.keyval('devices',k,'defs'):
                        try:
                            v = int(v)
                        except ValueError:
                            v = '"{}"'.format(v.replace('\\','\\\\').replace('"','\\"'))
                        else:
                            if not v:
                                continue

                        print("#define {} {}".format(a.upper(),v), file=f)

                    ow = s.subtree('devices',k,'defs','is_onewire')
                    if ow:
                        print("#define HAVE_ONEWIRE 1", file=f)

                    max_t = -1
                    for a,v in s.keyval('devices',k,'types'):
                        v = int(v)
                        if v > 0:
                            print("#define TC_{} {}".format(a.upper(),typecode[a]), file=f)
                            print("#define N_{} {}".format(a.upper(),v), file=f)

                            if max_t < typecode[a]:
                                max_t = typecode[a]
                    print("""\
#define MAX_TC {}

#endif /* device_{}_config_h */
    """.format(max_t,k,k), file=f);
            elif mode == "type":
                print(" ".join("{} {}".format(a,v) for a,v in s.keyval('devices',k,'types')))
            elif mode == "cdefs":
                types = dict((a,int(v)) for a,v in s.keyval('devices',k,'types') if int(v) > 0)
                maxtype = max(())
                print(" ".join("-D{}=\"{}\"".format(a.upper(),str(v).replace('"','\"')) for a,v in s.keyval('devices',k,'defs')) + " " + " ".join("-DN_{}={}".format(a.upper(),v) for a,v in s.keyval('devices',k,'types') if int(v) > 0))
            elif mode == "cfiles":
                files = ['dev_data.c','main.c','jmp.S']
                if s.subtree('devices',k,'defs','have_uart'):
                    files.append('uart.c')
                ow = s.subtree('devices',k,'defs','is_onewire')
                if not ow: pass
                elif ow in ('moat','ds2423','ds2408'):
                    files.append(ow+'.c')
                    files.append('onewire.c')
                else:
                    print("Unknown onewire mode:",ow, file=sys.stderr)
                    sys.exit(2)
                if not s.subtree('devices',k,'defs','use_eeprom'):
                    files.append('config.o')
                for f in s.subtree('devices',k,'code'):
                    files.append(f+'.c')

                print(" ".join(files))
            else:
                print("Unknown mode:",mode, file=sys.stderr)
                sys.exit(2)
    else:
        import pprint
        pprint.pprint(s.data)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: {} file [type] [key…]".format(sys.argv[0]), file=sys.stderr)
        sys.exit(2)
    main(*sys.argv[1:])
